spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=Vinayak@1844

# auto create tables
spring.jpa.hibernate.ddl-auto=update   

#print queries
spring.jpa.show-sql=true